"""Task 3 modifications

Revision ID: be01796e8aac
Revises: 2824123cb5a9
Create Date: 2026-09-02 13:18:59.423399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be01796e8aac'
down_revision: Union[str, Sequence[str], None] = '2824123cb5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_answers', sa.Column('answer_status', sa.String(length=50), nullable=False))
    op.add_column('consultations', sa.Column('session_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('clinical_field', sa.String(length=100), nullable=True))
    op.alter_column('questions', 'question_text',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               postgresql_using='question_text::jsonb')
    op.create_unique_constraint(None, 'questions', ['question_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.alter_column('questions', 'question_text',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('questions', 'clinical_field')
    op.drop_column('consultations', 'session_state')
    op.drop_column('clinical_answers', 'answer_status')
    # ### end Alembic commands ###
